services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # qBittorrent
    volumes:
      - /volume2/docker/gluetun:/gluetun
    environment:
      - PUID
      - PGID
      - TZ
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${SURFSHARK_WG_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${SURFSHARK_WG_ADDRESSES}
      - SERVER_COUNTRIES
      - SERVER_CITIES
      - FIREWALL_OUTBOUND_SUBNETS
    network_mode: synobridge
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped
      
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID
      - PGID
      - TZ
      - WEBUI_PORT=8090
      - UMASK=022
    volumes:
      - /volume2/docker/qbittorrent:/config
      - /volume1/data/torrents:/torrents
    depends_on:
      - gluetun
    network_mode: service:gluetun # run on the vpn network
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped