services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    restart: unless-stopped
    environment:
      - PUID
      - PGID
      - TZ
    ports:
      - 8945:8945
    security_opt:
      - no-new-privileges:false
      - seccomp:unconfined
    volumes:
      - /volume2/docker/pinchflat/config:/config:rw
      - /volume1/data/media:/downloads:rw
    network_mode: synobridge