services:
  changedetection:
    image: dgtlmoon/changedetection.io:latest
    container_name: changedetection
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - /volume2/docker/changedetection/datastore:/datastore
    environment:
      - PUID
      - PGID
      - TZ
    network_mode: synobridge