services:
  karakeep-app:
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: karakeep-app
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /volume2/docker/karakeep/data:/data
    environment:
      - PUID
      - PGID
      - MEILI_ADDR=http://karakeep-meilisearch:7700
      - BROWSER_WEB_URL=http://karakeep-chrome:9222
      - NEXTAUTH_SECRET
      - MEILI_MASTER_KEY
      - NEXTAUTH_URL
      - DATA_DIR=/data
      - CRAWLER_STORE_SCREENSHOT=true
      - CRAWLER_FULL_PAGE_SCREENSHOT=true
      - CRAWLER_ENABLE_ADBLOCKER=true
      - DISABLE_SIGNUPS=true # Was added after initial Admin user had been created
      - OLLAMA_BASE_URL
      - INFERENCE_TEXT_MODEL
    network_mode: synobridge

  karakeep-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    network_mode: synobridge

  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep-meilisearch
    restart: unless-stopped
    environment:
      - PUID
      - PGID
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY
    volumes:
      - /volume2/docker/karakeep/meilisearch:/meili_data
    network_mode: synobridge